### ISSUE TITLE
Problem accessing data

### ISSUE THREAD

**Issue by leem32** [io-developer/php-whois#111]
This might be obvious but I can't see anything in the docs.
How do I access the registrant, admin, tech info?
Also in previous issues, I can see people are accessing some of the data like: `$info->getDomainName()`, but the docs examples access the data like `$info->domainName`. Are there any differences between the two?

Using the example in the docs I can access only some of the data. For example `$info->adminEmail` returns empty string.

```php

use Iodev\Whois\Factory;
$whois = Factory::get()->createWhois();
$info = $whois->loadDomainInfo("google.com");
var_dump($info);
print_r([
    'Domain created' => date("Y-m-d", $info->creationDate),
    'Domain expires' => date("Y-m-d", $info->expirationDate),
    'Domain owner' => $info->owner,
    'Registrar' => $info->registrar,
    'nameServers' => $info->nameServers,
    'registrar' => $info->getRegistrar() ?: 'N/A',
    'domainName' => $info->getDomainName(),
    'domainName2' => $info->domainName,
    'states' => $info->states,
]);

```

**Comment by io-developer** [comment]
Greetings

1. Difference between $info->getDomainName() and $info->domainName: reading via methods are deprecated in 4.* versions (https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Modules/Tld/TldInfoDeprecated.php), use access via properties
2. This lib guarantees parsing only few primary fields (such as domainName, owner and etc). And this part has test-coverage
3. Raw parsed fields (admin_info and etc) could be accessed via `TldInfo::getExtra()` (https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Modules/Tld/TldInfo.php#L70) and `TldInfo::getExtraVal()` (https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Modules/Tld/TldInfo.php#L80). But no any warranty, its raw-parsed data and some fields may be not parsed (manual checking needed anyway).

Just request some domain info and print for debug what `TldInfo::getExtra()` contains. For example `var_dump($domainInfo->getExtra())`

**Comment by leem32** [comment]
That works, thanks.

I access like this:

```php

use Iodev\Whois\Factory;

$whois = Factory::get()->createWhois();

$info = $whois->loadDomainInfo("google.com")->getExtra();

var_dump($info);


```

**Comment by io-developer** [comment]
Very good :)
