### ISSUE TITLE
[feature] using library as a parser via StringLoader

### ISSUE THREAD

**Issue by deepika-maj** [io-developer/php-whois#122]
Is it possible for you to add another loader, something like below, so that the library can be used as a parser without doing actual whois query.

```php
<?php

namespace Iodev\Whois\Loaders;

class StringLoader implements ILoader
{
    private $whoisText;

    public function loadText($whoisHost, $query)
    {
        return $this->whoisText;
    }

    public function setWhoisText($whoisText)
    {
        $this->whoisText = $whoisText;
    }
}
```

which can be used as:
```php
$whoisClient = Factory::get()->createWhois(new StringLoader());

foreach ($records as $record) {
    $whoisClient->getLoader()->setWhoisText($record['raw_whois_text']);
    $whois = $whoisClient->loadDomainInfo($record['domain']);

    // app logic
}
```

**Comment by mewejo** [comment]
Bit late @deepika-maj, but you could do that with a custom loader as is. Just set your text on the loader and call the `loadDomainInfo()` with a generic domain.

**Comment by io-developer** [comment]
https://github.com/io-developer/php-whois/blob/master/tests/Iodev/Whois/Loaders/FakeSocketLoader.php
