### ISSUE TITLE
Notice: iconv(): Detected an illegal character

### ISSUE THREAD

**Issue by smkbd** [io-developer/php-whois#126]
**PHP-Whois version**: 4.0

**PHP version**: 7.4.4

**Description**  
This may be a problem related with character encoding. I get a PHP notice like this-
`Notice: iconv(): Detected an illegal character in input string in C:\xampp\htdocs\test\io-developer-whois\vendor\io-developer\php-whois\src\Iodev\Whois\Helpers\TextHelper.php on line 24`

**How to reproduce**  
Just load the domain 'airtel.com' like this-
`$info = $whois->loadDomainInfo("airtel.com");`

**Possible Solution**  
I know that's not a fix, but I am currently suppressing the notice by this (until there is fix the devs)-
`$info = @$whois->loadDomainInfo("airtel.com");`

**Comment by io-developer** [comment]
Can't reproduce. Maybe already fixed...
