### ISSUE TITLE
Hey getting ["Registrant Name"]

### ISSUE THREAD

**Issue by nam-co** [io-developer/php-whois#128]
Hi, thanks for the work on the great package, I was wondering how can I get the ["Registrant Name"], normally the registrant personal name

Thanks

**Comment by io-developer** [comment]
Hi. Check this out, if I understand question correctly it would help - https://github.com/io-developer/php-whois/issues/111

**Comment by nam-co** [comment]
Hi, thanks for the answer, I saw the post but it didn't work, Im just looking to get the "Admin Name", appreciate the help

**Comment by sirkokoenig** [comment]
Any news on this?

**Comment by nam-co** [comment]
Hi @sirkokoenig I just got back to. this and got it working this way:

```
$data = $whois->loadDomainInfo($domain);
$extra = $data->getExtra()['groups'][0];
$owner_email = $extra['Registrant Email'] or name or phone
```
