### ISSUE TITLE
Problem with .es domain name. is always available.

### ISSUE THREAD

**Issue by Dave-09** [io-developer/php-whois#131]
A customer of ours wanted to register a domain name which would be available according to our check. However, this is not true. Can you check and fix this?

As an example, you can use dominios.es.

Thank you!

**Comment by bessone** [comment]
If from the same machine you do a shell whois what result do you have?
I tested the library my local version and the result is correct.

Has your IP address been credited? The nic.es has a rather restrictive policy.
More info on #73

**Comment by Dave-09** [comment]
Hello,
