### ISSUE TITLE
Using github actions instead of Traivs

### ISSUE THREAD

**Issue by zaherg** [io-developer/php-whois#137]
Hey,

How do you feel about using Github actions instead of Travis?
I have been using it on a fork and it works nice

![image](https://user-images.githubusercontent.com/27624/111900653-dcb21680-8a44-11eb-93a7-d819308066d7.png)

this way we have everything in one place.

**Comment by io-developer** [comment]
Hi, looks good.
Didn't learn about it. Is it easy migrate from travis?

**Comment by zaherg** [comment]
it is easy, have a look at here https://github.com/darawish/php-whois/blob/master/.github/workflows/testing.yml

if you like, I can send you a PR (contains many things that you may not like or approve :D) which contain this one and also a small fixes for two issues I encountered.

**Comment by io-developer** [comment]
Done
