### ISSUE TITLE
Response chunk cannot be read for CZ whois lookup

### ISSUE THREAD

**Issue by mikaelz** [io-developer/php-whois#139]
**PHP-Whois version**: https://github.com/io-developer/php-whois/commit/34e268ab38af9f47583458772b8353ed450cb44f

**PHP version**: 7.2

**Description**  
Started getting randomly `Response chunk cannot be read`
in /var/www/vendor/io-developer/php-whois/src/Iodev/Whois/Loaders/SocketLoader.php on line 71

**How to reproduce**  
Whois lookup cz domain

**Comment by kornrunner** [comment]
This should be sorted in [4.1.1 release](https://github.com/io-developer/php-whois/releases/tag/4.1.1)

**Comment by io-developer** [comment]
Can't confirm the bug
