### ISSUE TITLE
whois server query ban by registry

### ISSUE THREAD

**Issue by erichuang2015** [io-developer/php-whois#14]
I request donuts domain as below :

require_once 'vendor/autoload.php';
use Iodev\Whois\Whois;

$response = Whois::create()->lookupDomain("google.associates");
echo $response->getText();

I got denied msgs as below:

Malformed request. Terms of Use: Users accessing the Donuts WHOIS service must agree to use the data only for lawful purposes, and under under no circumstances use the data to: Allow, enable, or otherwise support the transmission by e-mail, telephone, or facsimile of mass unsolicited, commercial advertising or solicitations to entities other than the registrar's own existing customers. Enable high volume, automated, electronic processes that send queries or data to the systems of Donuts or any ICANN-accredited registrar, except as reasonably necessary to register domain names or modify existing registrations. When using the Donuts Whois service, please consider the following: The Whois service is not a replacement for standard EPP commands to the SRS service. Whois is not considered authoritative for registered domain objects. The Whois service may be scheduled for downtime during production or OT&E maintenance periods. Queries to the Whois services are throttled. If too many queries are received from a single IP address within a specified time, the service will begin to reject further queries for a period of time to prevent disruption of Whois service access.

I am not sure if  this issue impacts other newgtld whois query.

**Comment by io-developer** [comment]
Problem was found in two sequential queries: the first is primary "google.associates". But if info can't be parsed querying the second "=google.associates".
If both can't be parsed returning the second. After fix returning the primary.

The screenshot of linux cli whois and the same response of php-whois after fix:
![image](https://user-images.githubusercontent.com/6779324/37848332-cc0aa5cc-2ee4-11e8-9a56-306b05185479.png)

You can check the changes in 'dev' branch

**Comment by erichuang2015** [comment]
fixed version tried for php-whois/src/Iodev/Whois/Whois.php

but got errors 

Fatal error: Call to undefined method Iodev\Whois\Loaders\SocketLoader::loadText() when tried $response->getText();

**Comment by io-developer** [comment]
You doing something wrong.. Clone the latest repo from dev branch and try this code:
```php
<?php

use Iodev\Whois\Whois;

require_once 'vendor/autoload.php';

$response = Whois::create()->lookupDomain("google.associates");
var_dump("\n{$response->getText()}\n");
```

**Comment by erichuang2015** [comment]
yes. I updated all the files, it works

**Comment by io-developer** [comment]
Good, issue resolved
