### ISSUE TITLE
Punycode and .no TLD does not work?

### ISSUE THREAD

**Issue by sttrsttr** [io-developer/php-whois#141]
Searching for почта.рф works fine.
Searching for sørlandet.com works fine.
Searching for frøysnes.net works fine.
Searching for frøysnes.no gives no results, but domain is registered according to norid.no

I've also tried passing the already punycoded string to the function, but that does not help.

Any clues?

print $whois->loadDomainInfo("xn--frysnes-r1a.no"); // Does not work
print $whois->loadDomainInfo("frøysnes.no"); // Does not work
print $whois->loadDomainInfo("xn--frysnes-r1a.com"); // Works fine
print $whois->loadDomainInfo("frøysnes.com"); // Works fine

**Comment by sttrsttr** [comment]
Edit:

Replaced 
  {"zone": ".no", "host": "whois.norid.no", "parserType": "block"},
with
  {"zone": ".no", "host": "whois.norid.no"},

And it worked fine

**Comment by io-developer** [comment]
Got response (cannot be parsed --> null info):
```
domain = "xn--frysnes-r1a.no"
host = "whois.norid.no"
query = "xn--frysnes-r1a.no\r\n"
text = "% By looking up information in the domain registration directory\n% service, you confirm that you accept the terms and conditions of the\n% service:\n% https://www.norid.no/en/domeneoppslag/vilkar/\n%\n% Norid AS holds the copyright to the lookup service, content,\n% layout and the underlying collections of information used in the\n% service (cf. the Act on Intellectual Property of May 2, 1961, No.\n% 2). Any commercial use of information from the service, including\n% targeted marketing, is prohibited. Using information from the domain\n% registration directory service in violation of the terms and\n% conditions may result in legal prosecution.\n%\n% The whois service at port 43 is intended to contribute to resolving\n% technical problems where individual domains threaten the\n% functionality, security and stability of other domains or the\n% internet as an infrastructure. It does not give any information\n% about who the holder of a domain is. To find information about a\n% domain holder, please visit"
```

Any ideas?

**Comment by sttrsttr** [comment]
What does the results look like when you remove "parserType": "block", since that solved the issue on my side.

**Comment by io-developer** [comment]
It works. I don't understand :)
Ok, see later...

**Comment by io-developer** [comment]
Fixed in https://github.com/io-developer/php-whois/commit/4b42ae9b3991995a9cfeec11f0fbe6d240713051
