### ISSUE TITLE
!Org question: is it a good idea transfer this project to free org account (io-develop) for developer team creation?

### ISSUE THREAD

**Issue by io-developer** [io-developer/php-whois#150]
Hello everyone!

I see this project is more or less interesting for people. I'd like to develop it, but I have no enough free time, sorry :(

So here is idea how this situation can be solved:
* Move this repository from https://github.com/io-developer into https://github.com/io-develop
* Create core team and add co-mantainer / co-developers
* ...

Profits:
* More independent collaboration
* Faster way to solve issues and apply PRs

Possible issues:
* I don't know how to do it smooth and right with no breaking (composer integration and etc.)
* Different views on project future
* Collision / conflicts

You're welcome to left your thougts.

@bessone you're number one candidate to be co-mantainer. What do you think?

**Comment by dcblogdev** [comment]
I've been using this package heavily in one of my projects I'm happy to support this however I can.

You can transfer from settings to an org account which will transfer everything over and GIT will automatically redirect the URLs as I understand it:

>All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL.

https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/transferring-a-repository

**Comment by io-developer** [comment]
It's good. However `composer.json` should be updated by users I guess (for long term cases)
For now I have composer page here - https://packagist.org/packages/io-developer/php-whois
I guess new page should be created also too (for long term cases)

**Comment by dcblogdev** [comment]
yeah if I remember correctly I think packagist follows the internal redirects as well. It would be better if users used the newer vendor name tho.
