### ISSUE TITLE
TypeError: trim()

### ISSUE THREAD

**Issue by amirmnoohi** [io-developer/php-whois#153]
**PHP-Whois version**: 4.1.0

**PHP version**: 8.0.7

**Description**  
I got an error which you can see below:
TypeError: trim(): Argument #1 ($string) must be of type string, array given in file C:\xampp\x\x\vendor\io-developer\php-whois\src\Iodev\Whois\Helpers\DateHelper.php on line 14

**How to reproduce**  
just test domain availability on asdfghj.com

**Comment by io-developer** [comment]
Fixed in master

**Comment by amirmnoohi** [comment]
again same thing happened with the domain "www.co"

below you can see the error:
```
"message": "Array to string conversion",
    "exception": "ErrorException",
    "file": "/home/x/vendor/io-developer/php-whois/src/Iodev/Whois/Helpers/GroupHelper.php",
    "line": 135,
```

**Comment by io-developer** [comment]
I see..

**Comment by io-developer** [comment]
Fixed. I think completely :)

**Comment by lucaros97** [comment]
Hi,
I got the same error with a com.tw domain.
`TypeError: trim(): Argument #1 ($string) must be of type string, array given`

PHP-Whois version: 4.1.3
