### ISSUE TITLE
Undefined Type Iodev\Whois\Factory

### ISSUE THREAD

**Issue by b1tw0rker** [io-developer/php-whois#157]
**PHP-Whois version**: 4.1

**PHP version**: 7.4.21

**Description**  
After installing the script as described i get these error: Undefined Type Iodev\Whois\Factory
Looks like, the namespace is nor registered correct.

Do i miss something ?

**Comment by io-developer** [comment]
Unit tests are working. So 99.9% issue on Your side.
Provide some details please.

**Comment by b1tw0rker** [comment]
Hi 

I installed the script as follows, with no errors.

composer require io-developer/php-whois

------------------------ 

in index.php i added: (as described in the Readme)

<?php

use Iodev\Whois\Factory;

// Creating default configured client
$whois = Factory::get()->createWhois();

// Checking availability
if ($whois->isDomainAvailable("google.com")) {
    print "Bingo! Domain is available! :)";
}

...
--------------


Folder structure is as follows:

-rw-r--r-- 1 testdomain001.de users  105 24. Jul 10:18 composer.json
-rw-r--r-- 1 testdomain001.de users 9,3K 24. Jul 10:18 composer.lock
-rw-r--r-- 1 testdomain001.de users  227 24. Jul 10:39 index.php
drwxr-xr-x 7 testdomain001.de users  105 24. Jul 10:18 vendor

composer.json looks:

{
    "require": {
        "io-developer/php-whois": "^4.1"
    }
}


------------------------------


I got the following error:

 PHP Fatal error:  Uncaught Error: Class 'phpWhois\\Whois' not found in /home/httpd/www.testdomain001.de/htdocs/whois/index.php
 
 Hope that helps ?

**Comment by io-developer** [comment]
You didnt include vendor/autoload in index.php before call 'use ..Factory;'

Check bootstrap for tests: https://github.com/io-developer/php-whois/blob/master/tests/bootstrap.php

**Comment by b1tw0rker** [comment]
YOU ARE RIGHT. THX a lot.

But wouldn't it be an idea to write it in the README also?

For those you are not so firm with composer, like me.

I am not working everyday with composer, so i suggested your script does not need autoload, when it is not written in the README!

**Comment by io-developer** [comment]
You're welcome :)

>> But wouldn't it be an idea to write it in the README also?
Actually it was but later I've removed.. Well maybe it needed to be recovered.
