### ISSUE TITLE
Problem with .uk / nominet

### ISSUE THREAD

**Issue by willpower232** [io-developer/php-whois#16]
This library is not working for .uk responses. I've done some debugging but you'll probably be able to figure it out faster than me.

As you know, `Whois->loadDomainDataFrom()` tries the whois server without strict and then with strict if it fails to parse the first attempt.

The `GroupHelper` fails to return the top half of the first (valid) nominet response so the parse fails and the strict attempt fails because nominet does not like the `=` at the start of the domain name and tells you this.

I believe the problem lies in `GroupHelper::groupFromText()` because I can see [here](https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Helpers/GroupHelper.php#L16) that it receives something like
```
string(37) "
    Domain name:
        bbc.co.uk"
```
and returns
```
array(1) {
  ["Domain name"]=>
  string(0) ""
}
```

Hope this makes sense.

**Comment by io-developer** [comment]
This is known problem because of not all whois responses can be parsed by existing parsers.
Many responses has similar structure to .UK so this issue in priority.
After some refactoring and test covering of BlockParser (in dev branch) I'll research this question.

Thanks for your reply :)

**Comment by io-developer** [comment]
Fixed in master
