### ISSUE TITLE
Deprecated function in PHP 8.1.2

### ISSUE THREAD

**Issue by dividerbeam** [io-developer/php-whois#182]
**PHP-Whois version**: 1.0.0

**PHP version**: 8.1.2

Deprecated
: Return type of Iodev\Whois\DataObject::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
/var/www/html/src/Iodev/Whois/DataObject.php
on line
68

public function jsonSerialize()
    {
        return $this->toArray();
    }

**Comment by io-developer** [comment]
Thanks =)
