### ISSUE TITLE
Timeout option

### ISSUE THREAD

**Issue by sirkokoenig** [io-developer/php-whois#187]
Maybe I didn´t find the option, but I want to set a manual timeout. Some servers aren´t answering and then the script will run over 30s...
I tried with CURL Loader, without success.

**Comment by bessone** [comment]
Have you tried with SocketLoader?
https://github.com/io-developer/php-whois/blob/9f93d372f2680f8185fb775cc71950dcdd9ce374/src/Iodev/Whois/Loaders/SocketLoader.php#L34
