### ISSUE TITLE
Problem with different domains from Europe.

### ISSUE THREAD

**Issue by newbie7777** [io-developer/php-whois#188]
Hi, I'm using the code and it's perfect, however I have a super dumb problem. Am I doing something wrong or am I making the wrong requests? When checking domains **.com** , **.me** I have no problem, but when I try to check **.bg(Europe)**.

Example:
google.com - works perfectly
google.bg - mmm, no 

Otherwise I manage to pull everything about the domain, full date even domain history using your code. What is the problem some gdpr or some data laws? :)
![work](https://user-images.githubusercontent.com/21267551/180229305-73552452-b20c-4027-a1f2-7161d7297faa.PNG)

**Comment by bessone** [comment]
This is normal, the whois server (**whois.register.bg**) does not return that information, as you can see in the raw text:

`DOMAIN NAME: google.bg (google.bg)
registration status: busy, active

NAME SERVER INFORMATION:
ns2.google.com
ns4.google.com
ns3.google.com
ns1.google.com

DNSSEC: inactive

According to REGULATION (EU) 2016/679 OF THE EUROPEAN PARLIAMENT AND
OF THE COUNCIL (GDPR) personal data is not published.

If you would like to contact the persons responsible for the domain
name, please, use the online WHOIS contact form from the "Info / Whois" menu
at www.register.bg.`

You can only understand if the domain is registered and see the authoritative DNS, the other information is not available.
