### ISSUE TITLE
Package true/punycode is abandoned, you should avoid using it.

### ISSUE THREAD

**Issue by JamesShaver** [io-developer/php-whois#190]
**Description**  
The true/punycode github is archived, and no longer maintained.  A replacement is suggested at:
[https://github.com/symfony/polyfill-intl-idn](https://github.com/symfony/polyfill-intl-idn)

**Comment by skiner68** [comment]
+1 one this. I have just removed true/punycode dependency from my project. Later it came back as third party dep when I needed to make some whois queries.

**Comment by mikedodd** [comment]
+1 on this, I really don't like having abandoned packages

**Comment by io-developer** [comment]
I can check it later. Maybe will fix it by myself..

**Comment by io-developer** [comment]
Merged
