### ISSUE TITLE
Expiration dates for .au domains

### ISSUE THREAD

**Issue by taat** [io-developer/php-whois#193]
**Description**  

The lookups for .au (Australian) domains do not return the expiration date information.

Is it possible to get this information somehow? Switch to a different server or something?

**Example**  

```
whois google.com
```
returns full information, including expiry date

```
whois google.au
```
does not include the expiration date info

```
$ whois google.au | grep -i date
Status: clientUpdateProhibited https://afilias.com.au/get-au/whois-status-codes#clientUpdateProhibited
>>> Last update of WHOIS database: 2022-11-01T11:47:47Z <<<
```

**Comment by lsthompson** [comment]
No, it's not possible. The Australian registry doesn't offer the information if you don't hold the Domain Password.
