### ISSUE TITLE
Other whois server host

### ISSUE THREAD

**Issue by ispweb** [io-developer/php-whois#199]
When i add:

`        $ServerWhois =TldServer::fromData([
            "zone" => ".nl",
            "host" => "rwhois.domain-registry.nl",
        ]);
        $whois->getTldModule()->addServers([$ServerWhois]);`

and do an lookup, it still uses whois.domain-registry.nl.

We want to change the whois server for our own domains to use a diffent as the default.

**Comment by io-developer** [comment]
Hi
You should insert it before default .nl - https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Configs/module.tld.servers.json#L782
Or remove default .nl from servers completely
