### ISSUE TITLE
globaltools.dk checking issue

### ISSUE THREAD

**Issue by andrii-pukhalevych** [io-developer/php-whois#200]
**PHP-Whois version**: 4.1.8

**PHP version**: 7.4, 8.1

**Description**  
Request of whois info for `globaltools.dk` produces error
`strtolower() expects parameter 1 to be string, bool given` in `src/Iodev/Whois/Helpers/TextHelper.php, line 15`

**How to reproduce**  
```
$whois = \Iodev\Whois\Factory::get()->createWhois();
$whoisInfo = $whois->loadDomainInfo($Entity->domain);
```

**Possible Solution**  
Issue happens after adding `declare(strict_types=1);` in `TextHelper.php`.
A possible solution is cast to string: `$srcEncoding = strtolower((string)mb_detect_encoding($text));`

**Comment by io-developer** [comment]
Thanks!
Fixed in https://github.com/io-developer/php-whois/commit/da224558cc50efc133d394c94556828f64884c24
