### ISSUE TITLE
Deprecated on PHP 7.1 still working as of now (not  a bug but how to fixed this warning popping sometimes on command line and page?)

### ISSUE THREAD

**Issue by tonz341** [io-developer/php-whois#23]
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Whois has a deprecated constructor in /home/vagrant/code/pixinpics/vendor/phpwhois/phpwhois/src/whois.main.php on line 31

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Whois has a deprecated constructor in /home/vagrant/code/pixinpics/vendor/phpwhois/phpwhois/src/whois.main.php on line 31
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; WhoisClient has a deprecated constructor in /home/vagrant/code/pixinpics/vendor/phpwhois/phpwhois/src/whois.client.php on line 30

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; WhoisClient has a deprecated constructor in /home/vagrant/code/pixinpics/vendor/phpwhois/phpwhois/src/whois.client.php on line 30
PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; idna_convert has a deprecated constructor in /home/vagrant/code/pixinpics/vendor/phpwhois/phpwhois/src/whois.idna.php on line 54

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; idna_convert has a deprecated constructor in /home/vagrant/code/pixinpics/vendor/phpwhois/phpwhois/src/whois.idna.php on line 54

**Comment by tonz341** [comment]
im using 3.0^ version thanks sir

**Comment by io-developer** [comment]
Well... this lib has no paths provided in your debug info.
Looks like warnings belongs to other project - https://github.com/phpWhois/phpWhois
:)

**Comment by tonz341** [comment]
sorry and thank you I already  fixed it. btw sir may i confirm if your
service you used is related from https://www.whois.com/ ?

i scan your config files seems there are so many urls that is whois may be
its your lookup server.

im trying to  look up whois url
creativeflooring.nz
and returning null.

did I misconfigured something? some URL's are working some are not.

thank you sir and more powers

**Comment by tonz341** [comment]
I see,

Thank you sir. and more powers to your package.
You are the God's blessing for us small time developers/

**Comment by io-developer** [comment]
Thank you :)
By the way the library is open for improving and contributing (but code-style and commit-style are very strict)
