### ISSUE TITLE
isDomainAvailable return true when connection limit occurs

### ISSUE THREAD

**Issue by mysiar** [io-developer/php-whois#24]
**PHP-Whois version**: 3.0.3

**PHP version**: 7.2.5

**Description**  
Whois::create()->isDomainAvailable returns true after **WHOIS QUERY RATE LIMIT EXCEEDED**

**How to reproduce**  
run isDomainAvailable multiple time

**Comment by io-developer** [comment]
Reproduced only 'WHOIS LIMIT EXCEEDED'
Resolved in commit - https://github.com/io-developer/php-whois/commit/fda1cbac51e93a2081252d00af7827a1e96f8cdd
Response validation should detect 'WHOIS QUERY RATE LIMIT EXCEEDED' case also
