### ISSUE TITLE
.shop TLD support request

### ISSUE THREAD

**Issue by TimSparrow** [io-developer/php-whois#26]
**Description**  
Currently, php-whois cannot resolve whois servers for .shop domain

**Workaround**
$customServers = [
	new TldServer(".shop", "whois.nic.shop", false, TldParser::create()),
];
$whois = Whois::create();
$whois->getTldModule()->addServers($customServers);

Is there a dev version supporting these domains? Or should I make it and create a pull request?

Edit: frl IS available, only .shop is not supported by default.

**Comment by TimSparrow** [comment]
Also, is a "default" whois server as a last-resource before issuing an exception planned? Some other libs do have this feature.

**Comment by io-developer** [comment]
>> Is there a dev version supporting these domains? Or should I make it and create a pull request?
The pull requests with config improvements are welcome =)

>> Also, is a "default" whois server as a last-resource before issuing an exception planned? Some other libs do have this feature.
It's good idea about default fallback server!

**Comment by TimSparrow** [comment]
OK, I will submit code with .shop support for pull request.

**Comment by TimSparrow** [comment]
Thanks, the issue is closed.

**Comment by io-developer** [comment]
Implemented default/fallback server defining.
Please check in README section **TLD default/fallback servers**
