### ISSUE TITLE
False positive result for .eu domains

### ISSUE THREAD

**Issue by TimSparrow** [io-developer/php-whois#27]
**PHP-Whois version**:3.0.5

**PHP version**: 5.6, 7.1

**Description**  
php-whois returns that google.eu is available (also happens with apple.eu)

**How to reproduce**  
Whois::create()->isDomainAvailable('google.eu') returns true, expected false;

**Possible Solution**  

**Additional context**  
**whois google.eu** 

returns no status.
Maybe it helps to debug the problem

> 

% WHOIS google.eu
Domain: google.eu

Registrant:
        NOT DISCLOSED!
        Visit www.eurid.eu for webbased whois.

Onsite(s):
        NOT DISCLOSED!
        Visit www.eurid.eu for webbased whois.

Registrar:
        Name: MarkMonitor Inc.
        Website: https://www.markmonitor.com/

**Comment by io-developer** [comment]
Thanks, I'll check it
