### ISSUE TITLE
Possibility to disable writing file

### ISSUE THREAD

**Issue by repat** [io-developer/php-whois#32]
**Reason**
> {"reason":"file_put_contents(domain.tld\r\n.txt): failed to open stream: Permission denied...

Using your project with Laravel and it's not possible to write the file like  that. Also don't see a reason for it.

**Description**  
A possibility to disable writing the file in `vendor/io-developer/php-whois/src/Iodev/Whois/Loaders/SocketLoader.php`: 40

```php
file_put_contents("$query.txt", $text);
```

Also, the query is sometimes:

```
 -T dn,ace repat.de

```

Including the paragraph as `\r\n`. So the filename has a paragraph in it. It would be good to  at least `trim()` it.

**Example**  
```php
$writeFlag = false;
Whois::create()->loadDomainInfo($domain, $writeFlag);
...
if ($writeFlag) {
  file_put_contents("$query.txt", $text);
}
```

**Comment by io-developer** [comment]
Oops.. Sorry for the lost debug dumping.
Fix committed and version updated.

**Comment by repat** [comment]
That was super fast, thank you! :)
