### ISSUE TITLE
function outdated

### ISSUE THREAD

**Issue by erichuang2015** [io-developer/php-whois#33]
**PHP-Whois version**: current version from the main branch

**PHP version**: 7.2

**Description**  
domain availability check

**How to reproduce**  
Deprecated: idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated in /www/wwwroot/www.mydomain.com/vendor/io-developer/php-whois/src/Iodev/Whois/Helpers/DomainHelper.php on line 32
**Possible Solution**  
function outdated

**Additional context**

**Comment by io-developer** [comment]
Seems like floating bug...
Please provide results of this code in your PHP 7.2:
1. `var_dump(defined("INTL_IDNA_VARIANT_UTS46"));'`
2. 'phpinfo()'

**Comment by erichuang2015** [comment]
1.   bool(false)
2 php-intl  is active in php

https://wiki.php.net/rfc/deprecate-and-remove-intl_idna_variant_2003

**Comment by io-developer** [comment]
Please attach full output of phpinfo();
