### ISSUE TITLE
whois script performance

### ISSUE THREAD

**Issue by erichuang2015** [io-developer/php-whois#34]
**PHP-Whois version**: current main version

**PHP version**: 5.5

**Description**  
 Checking availability query at low performance

**How to reproduce**  
I debug the running time for the code below 

if (Whois::create()->isDomainAvailable("google.com")) {
    print "Bingo! Domain is available! :)";
}

I can see that this domain  query runs really slow , it will consume around 2-3 seconds per request.
**Possible Solution**  
whois server query socket optimize

**Additional context**

**Comment by io-developer** [comment]
1. Is default config using for .com zones?
2. CPU loaded at 100% per php-whois process?
3. How many seconds executing native CLI 'whois google.com'?

**Comment by erichuang2015** [comment]
it seems that only .com whois server query load really slow

**Comment by liyo** [comment]
I can confirm this from AWS instances only.

**Comment by io-developer** [comment]
Hmm.. I'll check it.
The IANA WHOIS Server: whois.verisign-grs.com
Very strange why centralnic is first

**Comment by TimSparrow** [comment]
Confirm - I experience the same issue for .com and .net
Solution is to furce verisign-grs as a custom server.

**Comment by io-developer** [comment]
Fixed - https://github.com/io-developer/php-whois/commit/4b034f022db1ec08bf544d97a804dfe4675c5175
