### ISSUE TITLE
custom parser

### ISSUE THREAD

**Issue by erichuang2015** [io-developer/php-whois#35]
some tlds are not parsed correctly, such as .cm ,Domain owner is not parsed 

I just add key words for .cm "International Organisation" in /src/Iodev/Whois/Configs/ , but not work

**Comment by erichuang2015** [comment]
library is the current dev version
php 7.2
all of .cm domain owners not parsed
empty response from the default parser
International Organisation line should be parsed in whois data

**Comment by io-developer** [comment]
pushed to master
