### ISSUE TITLE
.be false "taken" report

### ISSUE THREAD

**Issue by TimSparrow** [io-developer/php-whois#36]
**PHP-Whois version**: 3.2.1

**PHP version**: 5.6.38

**Description**  
php-whois always reports "busy" when querying **.be** domains

**How to reproduce**  
Query: Whois::create()->isDomainAvailable('somedomainthatdoesnotexist.be');

Expected result: free
Actual result: busy

**Additional context**  
Note: whois server is configured correctly, but whois console command returns a correct result

**Comment by TimSparrow** [comment]
Please advise, where should I look to resolve the issue.

**Comment by TimSparrow** [comment]
created google.be.txt and free.be.txt by running:
`whois google.be > ./google.be.txt`
`whois somelonginexistentdomain.be > ./free.be.txt`

Uncommented the referenced section in TldParsingTest

Run 

- composer install (OK)
- composer run test

Error: 
1) Iodev\Whois\Modules\Tld\TldParsingTest::test_BE
InvalidArgumentException: File '/home/timofey/dev/www/hostingdirect/application/libraries/vendor/io-developer/php-whois/tests/Iodev/Whois/Modules/Tld/parsing_data/.be/google.be.json' not found

Where can I find that "google.be.json" file? It is not a part of the repository.

Additionally, it reported 207 test fails.

**Comment by io-developer** [comment]
'/io-developer/php-whois/tests/Iodev/Whois/Modules/Tld/parsing_data/.be/google.be.json' not found
It should be created with expected resulst based on /parsing_data/.be/google.be.txt

**Comment by TimSparrow** [comment]
Created google.be.json from google.com.json.
Tests fail with all stock parsers (errors are different).
Will resume testing tomorrow.

**Comment by io-developer** [comment]
Test covered in commit https://github.com/io-developer/php-whois/commit/ee505dbf0bc643f9b9feada952309294378dfd4b
