### ISSUE TITLE
Whois server name return

### ISSUE THREAD

**Issue by TimSparrow** [io-developer/php-whois#38]
**Description**  

When using the library, one cannot tell which server has returned the result. It could be an advantage to have a possibility to query the name of the server that has served the last request, to see if something goes wrong.

**Example**  

```
$ts = microtime(true);
$domain = 'somedomain.tld';
$result = $this->whois->isDomainAvailable($domain) ? 'free' : 'busy';
$elapsed = microtime(true) - $ts;
$serverName = $this->whois->getLastServer(); // New method that returns the server name responsible for the last result
$this->log(sprintf(
  "Whois data for %d was served by %s, resullt:%s, obtained in %f seconds", 
  $domain, 
  $serverName, 
  $result, 
  $elapsed
));
```

**Comment by io-developer** [comment]
Added in https://github.com/io-developer/php-whois/commit/8f620163da45cac2f0671f54d161b868af40ce6d
Also used parser type added to DomainInfo - https://github.com/io-developer/php-whois/commit/fddcff3abe65dc64333353c02083cd1bc847bc88
