### ISSUE TITLE
loadDomainInfo() returns null for .nz domains

### ISSUE THREAD

**Issue by jespinal** [io-developer/php-whois#42]
**PHP-Whois version**: 3.2.3

**PHP version**: 7.1

**Description**  
`loadDomainInfo()` method returns null for NZ domains

**How to reproduce**

So far the result has been consistent with all *.nz domains tested. Here's a list of the domains used for testing:

payrollmatters.co.nz
progressbuilders.co.nz
secuirty-services.co.nz
sgtc.org.nz
smarttech.nz
sparklife.net.nz
sticksxstones.co.nz
tasteofsun.co.nz
tenzo.fr
thequeencharlotte.co.nz
titanz.com.au
tradejacks.co.nz
triciaed.co.nz
tutoronline.co.nz
tvcontracting.co.nz
willdofitness.co.nz
wpnz.net.nz

Code snippet used:

```
<?php
use Iodev\Whois\Whois;
  
Whois::create();
  
// Getting raw-text lookup works
$response = Whois::create()->lookupDomain("payrollmatters.co.nz");
print $response->getText();
  
// Getting parsed domain info will not work
$info = Whois::create()->loadDomainInfo("payrollmatters.co.nz");
print_r([
    'Domain created' => date("Y-m-d", $info->getCreationDate()),
    'Domain expires' => date("Y-m-d", $info->getExpirationDate()),
    'Domain owner' => $info->getOwner(),
]);
?>
```

**Possible Solution** 
I think that something is not being detected by `Iodev\Whois\Modules\Tld\Parsers\CommonParser`

I ran the code with Xdebug and the keys used in the response in order to list the nameservers doesn't seem to be matched by any keys of the parser:

ns_name_01: ns1.somensserver.com
ns_name_02: ns2.somensserver.com

It may be that the response body format is different now.

**Comment by io-developer** [comment]
Thanks for report.
I'll check it.

**Comment by io-developer** [comment]
The fix pushed to master. Release will be little bit later.
Also `tenzo.fr` and `titanz.com.au` from your list are correct. There is no errors.
