### ISSUE TITLE
script crash down the servers

### ISSUE THREAD

**Issue by erichuang2015** [io-developer/php-whois#44]
**PHP-Whois version**: current stable

**PHP version**: 7.2.0
**Description**  
I am using script to query .cm domains such as xxx.cm, it seems that .cm whois server is down, and the script keep loading and wait fro the server response. during this period , script exausted the server resourses and go into 500 error.

**How to reproduce**  
require('vendor/autoload.php');
use Iodev\Whois\Whois;
use Iodev\Whois\Loaders\SocketLoader;
use Iodev\Whois\Loaders\MemcachedLoader;
use Iodev\Whois\Exceptions\ConnectionException;
use Iodev\Whois\Exceptions\ServerMismatchException;
use Iodev\Whois\Exceptions\WhoisException;
$m = new Memcached();
$m->addServer('127.0.0.1', 11211);
$loader = new MemcachedLoader(new SocketLoader(), $m);
try {
    $whois = Whois::create($loader);
    $info = $whois->lookupDomain("xxx.cm");
    print $info->getText();
} catch (ConnectionException $e) {
    print "Disconnect or connection timeout";
} catch (ServerMismatchException $e) {
    print "TLD server not found in current server hosts";
} catch (WhoisException $e) {
    print "Whois server responded with error '{$e->getMessage()}'";
}
**Possible Solution**  
custom timeout for query

**Additional context**

**Comment by io-developer** [comment]
I guess it can be done here - https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Loaders/SocketLoader.php#L23
Sorry, have no time to do it for now

**Comment by io-developer** [comment]
Improvements pushed to master

Now you can set timeout for DNS lookup and for socket connecting in SocketLoader (in constructor or call setTimeout())

**Comment by shaoweigege** [comment]
hello

this fix does not work, I get the lastest master codes to run. For example,I query to whois server whois.nic.lk, it will keep loading and loading,throw this error

Fatal error: Maximum execution time of 30 seconds exceeded in C:\mydev\WWW\vendor\io-developer\php-whois\src\Iodev\Whois\Loaders\SocketLoader.php on line 66

I do set timeout parameter here

 public function __construct($timeout = 10)
    {
        $this->setTimeout($timeout);
    }

actually it does not work

**Comment by io-developer** [comment]
Ok, I'll check it later.
Now you can try replace SocketLoader by new CurlLoader.
Please check master branch and readme updates.


сб, 9 мар. 2019 г., 13:01 shaoweigege <notifications@github.com>:

**Comment by shaoweigege** [comment]
Hi

you mean this way ?

use Iodev\Whois\Loaders\CurlLoader;
use Iodev\Whois\Whois;
$loader = new CurlLoader();
$whois = Whois::create($loader);
$response = $whois->lookupDomain("google.lk");
print $response->getText();

yes, curl method works

**Comment by io-developer** [comment]
Yes. It's correct code

сб, 9 мар. 2019 г., 13:48 shaoweigege <notifications@github.com>:
