### ISSUE TITLE
provide a way to bypass TLD rate limit

### ISSUE THREAD

**Issue by olaulau** [io-developer/php-whois#45]
making a few whois requests quickly leads to a rate limit, with random responses.

**Description**  
- maybe we can query another server that is a mirror of TLD, with less rate limit
- maybe we can load raw whois answer (and then parse it) we could have obtained from bulk whois website

**Example**  
https://www.bulkseotools.com/bulk-whois-lookup.php
https://dntoolz.com/tools/whois.php

**Comment by io-developer** [comment]
I guess the best way is to use this lib via proxy with multiple docker containers or something else.
The primary purpose of this lib is provide usable parsed whois responses.
For near future have no plans for mass parallel requests.

**Comment by io-developer** [comment]
Released v3.3.0 and added proxy support via CurlLoader (example in readme).
It maybe a valuable for you.

**Comment by io-developer** [comment]
I'll close due to requests can be passed through proxies
