### ISSUE TITLE
No servers matched for domain *.site

### ISSUE THREAD

**Issue by manchenkoff** [io-developer/php-whois#46]
**PHP-Whois version**: ^3.2

**PHP version**: 7.2.10

**Description**  
An error 'Iodev\Whois\Exceptions\ServerMismatchException' occurres when trying to check some **.site** by calling isDomainAvailable()

**How to reproduce**  
Call __Whois::create()->isDomainAvailable('some-website.site')__

**Possible Solution**  
Add .site domain zone checking server

**Comment by daveismyname** [comment]
What is the website address? I may have a fix but need a .site address to test but cannot find any on Google.

**Comment by manchenkoff** [comment]
here it is 'comeandsee.site'

**Comment by daveismyname** [comment]
your domains fails to load for me. When I visit it I see:

```
This page isn’t working comeandsee.site is currently unable to handle this request.
HTTP ERROR 503
```

I added 

```
{"zone": ".site", "host": "reg.com/whois"},
```

To the list of whois sites to test against.

**Comment by manchenkoff** [comment]
Great, I've just tried this server and everything is fine now, thanks

**Comment by io-developer** [comment]
Pushed to master
