### ISSUE TITLE
[RFC] A lot of data get lost only because not supported by DomainInfo (but they are present and correctly parsed!)

### ISSUE THREAD

**Issue by Aerendir** [io-developer/php-whois#50]
**Description**  
This library is really powerful and is able to create an array populated with every data returned by any whois server.

Those data are concretely available as array, but they get lost as the selector only selects part of them.

I'm referring, for example, to the response returned by NIC (the Italian whois), that contains a lot of data about the owner of the domain, including his address.

Unfortunately, the selector only selects a bunch of data to pass to the `DomainInfo` object and so those data are not accessible (but yet really useful.

Is it possible to add all not selected data to a parsed array to pass to `DomainInfo`?

This way, the current properties permit to access the common data, but it is anyway possible to access other information as needed, also if they not fit the standard properties of the `DomainInfo` object.

What do you think about this?

It maybe sufficient to add a fourth argument to the `DomainInfo` data that may be called something like `parsed` that contains the parsed `$response`.

Or it can be added to the `Response` object itself as `parsed` property, to pair with the property `text` already present.

Any solution will be useful: the real thing is to make accessible the response as a parsed array to use as anyone likes.

**Comment by io-developer** [comment]
First of all thanks for using this lib :)

I should know what exactly you request:
1. Get just raw parsed data as is, without any filtering. So you have to understand youre going to write your own parser for extracting some certain keys/values from this raw bunch of parsed data.
2. Get parsed extra data with some compatibility between responses from other whois servers.

First is real. Second seems to be impossible =)

**Comment by Aerendir** [comment]
First of all, thank you, too, for this very fast response! I was already resigned to go to write my own library! Instead, as you are very fast in replying and I see you are maintaining the library, may be, if you like, I can contribute to the yours one!

That said, what I'd like to get, is an array containing all the data the response from the whois contains.

Writing a universal object is, yes, nearly impossible as the information change a lot from whois to whois.

I think that the only thing possible to use a mix of interfaces and traits to try to universalize the information.

And some specific parsers based on the single whois, so it is possible to extract everithing from each one.

Further analyzing the responses, I noticed the following things:

1. There is always a creation date;
2. There is always an expiration date;
3. There are always the nameservers;
4. There are always the data about the registrar (its data is variable)
5. The data of a registrar can be
    1. Organization/Name
    2. Address (street 1, street 2, city, the postal code, state/province, country)
    3. Record creation date
    4. Record last update
6. Other information may be present, like
    1. the techincal contact
    2. the administrative contact,
7. Data about the registrant are variable

Now, given those information, it is possible to create `trait`s and `interface`s.

They will be used with dedicated `DomainInfo` objects that extend the main one:

1. `DomainInfoIT`
2. `DomainInfoNET`
3. `DomainInfoORG`
4. `DomainInfoCOM`
5. etc.

Each one has also a dedicated parser.

If there is no parser, then the one currently used will continue to be used; but if a more specific parser and object exist, then it will be used.

So, universalizing the keys is easy.

For example, it is possible to always call `Admin` the `Admin Contact` (NIC, .it domains) and the various keys about the admin present in the .net whois responses (`Admin Name`, `Admin Organization`, `Admin Street`, etc.).

**Comment by Aerendir** [comment]
As I anyway need those information in my application, I'm going to anyway create those specific parsers (not for all the TLD, obviously, but for the most common ones, for sure).

If you agree, I can send a PR with the result, so you will have a more clear understanding of what I'm saying and how I intend to implement all these things.

**Comment by io-developer** [comment]
Actually not quite all requests provides dates, address and etc.
For the first time I was think like that but then I decided to make test coverage too ensure all responses parses correctly. So I've put tons of possible answer here - https://github.com/io-developer/php-whois/tree/master/tests/Iodev/Whois/Modules/Tld/parsing_data
There you can find very exotic variants.

So I suppose to do:
1. Pass through raw-parsed data to DomaInfo just from parser and you can do some selection/filtering to get what you want from extra fields
2. After that think about DomainInfo fields extending such as org/admin address and etc. It's very complex question because it requires expand existing test coverage =/

**Comment by Aerendir** [comment]
Yes, I'm better studying your code and the thing is more complex than how it appeared in the first time...

Maybe the best thing I can do is to write some parsers for my own use and use your library only as a client for this specific use case.

Another thing I noticed is that you put in one big file all the possible keys in responses. I'm speaking about the file in `Configs/module.tld.parser.*`: this makes very complex to implement parser for each specific TLDs.

As a side note, I noticed also anther thing: both methods `Whois::lookupDomain()` and `Whois::loadDomainInfo()` call the private method `loadDomainData()`.

This means that, practically, both of them do always both the retrieval of information from the whois and the parsing, while for the domain lookup, only the retrieval of the response is required, making the parsing a waste of resources, doesn't it?

**Comment by io-developer** [comment]
About `Configs/module.tld.parser.*`:
I don't like that it's so big and will grow if new fields added. But it covers current requirements and it works.

About `Whois::lookupDomain()`:
Not all responses can be quickly decided domain exists or not. Sometime tld responds with custom fields even if domant not found. To be sure response must be parsed and checked for the primary fields such as domain name and state/status.

Also I don't like current requests pipeline. It seems very complex. But it works and no bug reports appears.


So about this enhancement:
> They will be used with dedicated DomainInfo objects that extend the main one:
> 
>     DomainInfoIT
>     DomainInfoNET
>     DomainInfoORG
>     DomainInfoCOM
>     etc.

Actually it's wrong way because response format depends of whois server, not of zone.
1. So if you extract subclasses from DomainInfo, primary whois not responding and reserved answered with custom format, you are get empty keys that are expected for .NET (for example).
2. Other reason .COM and .NET (.RU .РФ also) have the same format as I remember. So sub classes makes no sense or makes overcoding and redundant classes.
3. In .COM/.NET and other non-centralized zones could be custom whois server attached (usual it's registrant whois server) with complete information about domain and owner

So I suppose better way is still:
>   1.  Pass through raw-parsed data to DomaInfo just from parser and you can do some selection/filtering to get what you want from extra fields
>   2.  After that think about DomainInfo fields extending such as org/admin address and etc. It's very complex question because it requires expand existing test coverage =/

**Comment by io-developer** [comment]
> Maybe the best thing I can do is to write some parsers for my own use and use your library only as a client for this specific use case.

Check this out:
* https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Modules/Tld/Parsers/CommonParser.php#L75
* https://github.com/io-developer/php-whois/blob/master/src/Iodev/Whois/Modules/Tld/Parsers/BlockParser.php#L73

I guess you can extract anything if you get in DomainInfo these filters/selectors. What actually use can be resolved via DomainInfo::getParserType()

**Comment by Aerendir** [comment]
There are a lot of issues with whois, I'm discovering them! -.-'

Maybe the best approach is to create custom parsers just for my use cases (after all I will never query for the most of the TLDs that currently exist, only for the most common).

From what you write, a big part of the complexities come from the necessity of doing unit tests, and this is a correct approach.

So, given these difficulties, and given that currently I don't have a lot of experience with whois querying, for the moment I will try to understand better the complexities.

If I will come with a solution, I will inform you, hoping that the library can be improved (also if it is difficult, as it is really complete, anyway).

In the mean time, thank you very much for your responses, as they are putting me on the right direction!

**Comment by io-developer** [comment]
Well if you have only one zone (.it I guess) you could just:
* create `class CustomDomainInfo extends DomainInfo` and add your extra fields
* create class `CustomTldParser` and extend one of https://github.com/io-developer/php-whois/tree/master/src/Iodev/Whois/Modules/Tld/Parsers
* CustomTldParser::parseResponse() must return `CustomDomainInfo `
* Create `new Whois` instance and pass through your `CustomTldParser`
* profit :)

**Comment by Aerendir** [comment]
@io-developer , I don't have only one zone: for the moment I need to support it, com, org, net and maybe some other zones...

I will explore the solution you suggested me: thanks a lot for it! :)

**Comment by io-developer** [comment]
>  I don't have only one zone: for the moment I need to support it, com, org, net and maybe some other zones...
There is only 3 parsers for all zones. So you could extend their parseResponse() with extra fields parsing

> I will explore the solution you suggested me: thanks a lot for it! :)
You're welcome :)
