### ISSUE TITLE
Domain controle .jp didn't work

### ISSUE THREAD

**Issue by Dave-09** [io-developer/php-whois#52]
**PHP-Whois version**: 3.3.1

**PHP version**: 7.2

**Description**  
If you do a domain name check for *.jp it will always indicate 'available'.

**How to reproduce**  
Please check it with enjoymyjapan.jp. This domain name is taken, but does it indicate available? That is not true.

**Comment by Dave-09** [comment]
Problem also exist with google.co.jp.

**Comment by io-developer** [comment]
.jp has very different format. New parser and tests needed as I see.

**Comment by Dave-09** [comment]
Thank you for the information! can you fix and test that? then I want to test it for you afterwards.

**Comment by io-developer** [comment]
Sure. But later. I guess at the end of this week or on next

**Comment by io-developer** [comment]
Improvements pushed to this branch - https://github.com/io-developer/php-whois/tree/dev-improvements

**Comment by Dave-09** [comment]
Thank you! problem solved for enjoymyjapan.jp, but not for google.co.jp.

**Comment by io-developer** [comment]
> but not for google.co.jp
Actually google.co.jp has test case...

My bad: didn't checked realtime loading. .JP has specific query format.
You could pull latest commit from `dev-improvements` and check on your domains.

**Comment by Dave-09** [comment]
Thank you! now the problem is gone :) problem solved.
