### ISSUE TITLE
CurlLoader: curl_setopt(): cannot represent a stream of type MEMORY as a STDIO FILE*

### ISSUE THREAD

**Issue by olegbaturin** [io-developer/php-whois#53]
**PHP-Whois version**: x.y.z
3.3.1

**PHP version**: x.y.z
7.1.24

**Description**  
CurlLoader.php:97: curl_setopt_array(): cannot represent a stream of type MEMORY as a STDIO FILE*

**How to reproduce**  
$loader = new CurlLoader();
$whois = Whois::create($loader);

**Possible Solution**  
In the CurlLoader:82 replace
$input = fopen('php://memory','r+');
to
$input = fopen('php://temp','r+');

**Additional context**  
tested on Windows 8.1

**Comment by io-developer** [comment]
Is it Windows specific bug?

**Comment by olegbaturin** [comment]
I don't know. I found the same behavior and solution in other curl based libs.

**Comment by io-developer** [comment]
Pushed to master
