### ISSUE TITLE
lookups fails for .tn domains

### ISSUE THREAD

**Issue by alakameljebali** [io-developer/php-whois#55]
**PHP-Whois version**: 3.3.1

**PHP version**: 7.2.11

**Description**  
Cannot check a .tn domain owner or any other useful information

**Additional context**  
Output for "ati.tn": 
Array ( [Domain created] => 1998-01-06 [Domain expires] => 1970-01-01 [Domain owner] => )

**Comment by io-developer** [comment]
Improvements pushed to this branch - https://github.com/io-developer/php-whois/tree/dev-improvements

**Comment by io-developer** [comment]
pushed to master
