### ISSUE TITLE
[idea] using __call magic function in DomainInfo class

### ISSUE THREAD

**Issue by linuxjuggler** [io-developer/php-whois#61]
**Description**  
Each domain will return a load of information that we don't process, using `__call` function within the `DomainInfo` class will allow us to have dynamic functions that we can use.

**Example** 

1- First we need to add the following code to the `DomainInfo` class

```php
    // This function will return all the method names they can use
    public function getAvaliableKeys()
    {
        $keys = array_keys($this->data);

        foreach ($keys as $key) {
            $functions[$key] = 'get'.ucfirst($key);
        }

        return implode(', ',$functions);

    }

    public function __call($methodName, $arguments = '')
    {
        $method = lcfirst(substr($methodName, 3));
        
        if(array_key_exists($method, $this->data)) {
            return $this->getval($method, $arguments);
        }

        throw new \Exception("Method {$methodName} does not exists");
    }
```

2- Update the parsers (in my case here I've updated the `CommonParser` class to add new values, for example, I added the registrar company URL:
a) Add the key
```php
    /** @var array */
    protected $registrarUrlKeys = [ "registrar url" ];
```
b) update `parseResponse` function:
```php
    /**
     * @param DomainResponse $response
     * @return DomainInfo
     */
    public function parseResponse(DomainResponse $response)
    {
        $sel = $this->filterFrom($response)->toSelector();
        $data = [

// deducted for simplicity

            "registrarURL" => $sel->clean()
                ->selectKeys($this->registrarUrlKeys)
                ->getFirst(''),
        ];
        $info = new DomainInfo($response, $data, $this->getType());
        return $info->isValuable($this->notRegisteredStatesDict) ? $info : null;
    }
```

Now I can use the following code:

```php
    $whois = Whois::create();
    $info = $whois->loadDomainInfo('google.com');

    return $info->getRegistrarURL();
```
And I'll get the value `"http://www.markmonitor.com"` successfuly.

Now we can delete the following functions from `DomainInfo`:

```php
    /**
     * @return string
     */
    public function getDomainName();

    /**
     * @return string
     */
    public function getWhoisServer();

    /**
     * @return string[]
     */
    public function getNameServers();

    /**
     * @return int
     */
    public function getCreationDate();
```

And it will still work since they become dynamic functions. Also, whenever we add a new selector to the Parsers, it will be automatically available as a function without editing the `DomainInfo` class.

I am sure the code needs some cleanup, as this is just a draft idea.

**Comment by io-developer** [comment]
Looks good.
But general idea of get* methods it's provide minimal pack of information for every whois response.
Also it has no backward compability. Or old get* methods must decorate new magic calls inside.

**Comment by io-developer** [comment]
I guess this improvement should be in new major version "4"

**Comment by linuxjuggler** [comment]
> But general idea of get* methods it's provide minimal pack of information for every whois response (via static class interface).

True, but also such feature has the downside of not being able to pull any data the whois provider returns, in my case, for example, I wanted the registrar URL and I don't think there is any way for me to get that info without editing your code (I didn't dig deep within the code to know if there is a better way other than editing the code)

> Also it has no backward compatibility.

The new modifications will not have any effect on the old functions, as for example, the `getCreationDate` is going to function as it used to, as long as the key `creationDate` is part of the `data` array keys.

> Or old get* methods must decorate new magic calls inside.

Keeping the old methods will not have any effect, in the end, they are calling the `getval` methods which is what `__call` is using.

The only downside of this is that the IDE may not be able to provide an autocomplete for the functions, that's why I introduced `getAvaliableKeys` (maybe adding a dock block can fix this too, am not 100% sure)

**Comment by io-developer** [comment]
Implemented in v4 branch via `DataObject`
