### ISSUE TITLE
Using private visibility prevent extending

### ISSUE THREAD

**Issue by linuxjuggler** [io-developer/php-whois#63]
**PHP-Whois version** 3.x

**PHP version**: 7.x

**Description**  
Using private visibility for variables within the `Whois` class (as an example here) makes it very hard to extend and modify the class without editing the original class

For example, there is no way for us to modify the following variables

```php
    /** @var ILoader */
    private $loader;

    /** @var TldModule */
    private $tldModule;

    /** @var AsnModule */
    private $asnModule;
```

So there is no way for me to modify the `getTldModule` function, for example:

```php
    /**
     * @return TldModule
     */
    public function getTldModule()
    {
        $this->tldModule = $this->tldModule ?: TldModule::create($this->loader);
        return $this->tldModule;
    }
```

**How to reproduce**  
Create a new Class and try to extend the Whois class, then try to create a new function with the name `getTldModule`

**Possible Solution**  
1. Either to change it them `protected` (which I don't like much).
2. Provide a set of functions that we can use to modify those private variables without editing them directly like

```php
    public function setTldModule(TldModule $tldModule = null)
    {
        $this->tldModule = $this->tldModule ?: ((null ===$tldModule) ? TldModule::create($this->loader) : $tldModule);
    }
```
and change `getTldModule` function to only return the value instead of setting + returning the value

```php
    /**
     * @return TldModule
     */
    public function getTldModule()
    {
        return $this->tldModule;
    }
```

The function `getTldModule` should only return the data, not initiate it too.

Then whenever we call `getTldModule` in `isDomainAvailable`, `lookupDomain`, `loadDomainInfo` we call `setTldModule` before it for example `isDomainAvailable` will become:

```php
    /**
     * @param string $domain
     * @return bool
     * @throws ServerMismatchException
     * @throws ConnectionException
     * @throws WhoisException
     */
    public function isDomainAvailable($domain)
    {
        return $this->setTldModule()->getTldModule()->isDomainAvailable($domain);
    }
```

I am sure there are many places in the code like this one, but we can always start with the `Whois` class first, then move to other classes one by one.

I am more than happy to help you with this if you agree with me about this point.

**Additional context**  

![Screen Shot 2019-08-15 at 7 57 41 PM](https://user-images.githubusercontent.com/27624/63111735-010b5e80-bf97-11e9-983c-e72e533cfa8e.png)

**Comment by io-developer** [comment]
Well, it's very specific case I guess. Why do you want to override module creating?
I need some context to understand the reason.

Anyway I guess better way is pass to `Whois` constructor a second (or first and single) argument `WhoisFactory` that you could extend or replace any creation logic (Whois, TldModule, AsnModule)

Currently you can override logic - just use different name for $this->tldModule such as `tldModuleExtended` or whatever to avoid name collisions.

**Comment by linuxjuggler** [comment]
My main target is to extend `DomainInfo` class without overwriting the whole class and duplicate the code, and the same goes for `CommonParser` class.

What you have suggested might work (I need to test it), but it may also mean that I'll have to **duplicate** many functions so they use my variables instead of the default one.

Your code should consider making your code open for extension, but closed for modification.

**Comment by linuxjuggler** [comment]
You use the `private` scope too much, which makes it hard to extend mostly everything.
for example in the `DomainInfo` the `data` is private, the `getVal` function is private.

Any specific reasons why they are `private`?

**Comment by io-developer** [comment]
I support the idea of composition instead of extending for core arch.
Yes, you could extend Whois but what purpose is? It's a simple container for Tld and Asn module.
You just can instantiate custom-configured TldModule for special cases by the way.

About extending of DomaInfo. I agree, but without new Parser it's useless...

It's complex dilemma because all ways going to Parser modification...

**Comment by linuxjuggler** [comment]
This is the thing; I don't want to extend the Whois, my simple thought of adding a straightforward function for my project ended toward a rabbit hole where I have to extend/modify a lot of the code.

I don't need to add a new Parser when the current parser works like a charm but needs a bit of change.

I am not trying to change how you built the package, I really find it a good one which provides a great minimal unified data. am just so frustrated of the complexity I got myself into just to add a simple function.

**Comment by io-developer** [comment]
Thank you very much for a good words :)

Yes, I know. This is problem actually, because of have just one parser (which could be extended) this lib has 3.
I don't see any minimal solutions to parse extra keys now without library modification. Sorry :/

**Comment by linuxjuggler** [comment]
No worries man, I'll keep digging and hopefully, you will consider using SOLID principles in the next version as it will help anyone to extend the package.

I'll close the ticket for now.

Thanks again for your help 👍

**Comment by io-developer** [comment]
I recommend you determinate which parser is using for your purpose and add extra keys parsing to it.
Like that `\Iodev\Whois\Modules\Tld\Parsers\BlockParser::parseResponse`
Here we go:
![image](https://user-images.githubusercontent.com/6779324/63171786-f8716180-c044-11e9-85b2-13c394aee108.png)

**Comment by io-developer** [comment]
Yes, I want to open response/parsing part for user extension and modification.
But now it looks very complex due to specific parsing way.

**Comment by linuxjuggler** [comment]
> I recommend you determinate which parser is using for your purpose and add extra keys parsing to it.
> Like that `\Iodev\Whois\Modules\Tld\Parsers\BlockParser::parseResponse`
> Here we go:
> ![image](https://user-images.githubusercontent.com/6779324/63171786-f8716180-c044-11e9-85b2-13c394aee108.png)

This is what I used to do, but this requires editing the original core code or even create a similar file with the same NameSpace and everything to overwrite the one you are using.

I think I might found a way to extend your code and make it work for me.

Thanks man for every thing

**Comment by io-developer** [comment]
> This is what I used to do, but this requires editing the original core code or even create a similar file with the same NameSpace and everything to overwrite the one you are using.

Yeah, and I really don't like this situation.
Let me know if you find workaround

**Comment by linuxjuggler** [comment]
@io-developer I ended up extending the following classes

![Screen Shot 2019-08-16 at 5 54 10 PM](https://user-images.githubusercontent.com/27624/63176620-f01e2400-c04e-11e9-8fd5-50a0730d9fc9.png)

and modify the functions I want.

one of the big problems I faced is using `__NAMESPACE__` in the `TldParser` if you didn't use it, I wouldn't have to extend it at all.

The code I ended up is messy 🤪,  not clean 😭 , but it works for now.

**Comment by io-developer** [comment]
Wow, looks weird =)
Yeah, just ZIP these files and share somewhere. I'll check it out

**Comment by linuxjuggler** [comment]
Here you go check [src.zip](https://github.com/io-developer/php-whois/files/3510208/src.zip).

I ended up with a spaghetti code because I didn't want to edit the core :'(
if you can suggest any better solution, I would appreciate that, in the end you know your code better than I do

**Comment by linuxjuggler** [comment]
and it is not working as expected, I need to redo a lot of the code.

I might end up sending a PR to add the method I need into the core directly ;)

**Comment by io-developer** [comment]
Thanks, now I see the pain :/
Will try to improve extending in major version

**Comment by io-developer** [comment]
Try this one to customize your logic - https://github.com/io-developer/php-whois/commits/v4
I extracted main factory and factory methods in parsers. So it should be more friedly to extending.
It's not finished versions, so lots of changes will appear later

**Comment by linuxjuggler** [comment]
Thanks man 👍 , I'll check it and let you know.

if there is anything I can do let me know

**Comment by io-developer** [comment]
Currently I'm leisurely solving hard coded instantiating.
After that plans to refactor/rename a new code
So certain help not needed I guess.


Very interesting is your feedback about refactored code. Maybe some improvements/fixed needed

**Comment by linuxjuggler** [comment]
Just a small not for anyone who might read this post, if you are not going to use a Dependency injection library, you might face the same problems am facing.

Instead, you might consider using a Dependency injection like PHP-DI or if you are using Laravel/Lumen you might want to consider doing the replacement within your Application Service provider.

but this won't change the fact that using the private scope is need to change.

Kudos to @io-developer for the great work he has done for this package

**Comment by io-developer** [comment]
Thanks :)

I'm making changes in `v4` branch little by little if I have free time. So you can check it from time to time.

**Comment by linuxjuggler** [comment]
Thanks @io-developer , also it would be much better not to use the `create` static method and instead use a DI library, as this will make it even easier for people to change things.

I'll check v4 but now I need to release my code :D and am using v3 with many changes at my end to make things a bit easier.

**Comment by io-developer** [comment]
I'm very not sure that project needs DI. It's not too big to be managed via DI I guess. So I think factory is enough for this time,
Maybe to `v5` I'll change opinion. But now it's seems not necessary.

But thanks anyway, I'll read docs about PHP-DI lib little bit later.

**Comment by linuxjuggler** [comment]
Totally agree with you, simple and independent is the nice thing I found in your package. Kudos for that.
