### ISSUE TITLE
Dropping the Support for PHP 5.x & 7.0

### ISSUE THREAD

**Issue by linuxjuggler** [io-developer/php-whois#64]
**Description**  
The time has come to drop the support for [PHP 5.x ](https://www.php.net/eol.php) and 7.0.
We should push people to upgrade to a better and secure version of PHP.

**Comment by io-developer** [comment]
Definitly.
I have some ideas/plans for new major version 4 (but it not soon):
* Drop old PHP version support
* Update PHPUnit to latest version
* Improvements and changes in class interfaces that breaks backward compability

**Comment by linuxjuggler** [comment]
Ok, I'll close this ticket then.

Thanks
