### ISSUE TITLE
Problems with the Turkish domains .com.tr

### ISSUE THREAD

**Issue by linuxjuggler** [io-developer/php-whois#66]
**PHP-Whois version**: 3.4.1

**PHP version**: 7.3.x

**Description**  
When trying to get the WHIOS information about google.com.tr, they will return data like this

```shell
** Billing Contact:
NIC Handle		: btl1-metu
Organization Name	: Beril Teknoloji Bili�im Yay�nc�l�k Ticaret A.�.
Address			: Hidden upon user request
Phone			: Hidden upon user request
Fax			: Hidden upon user request
```

Which make it hard for the `TextHelper` class to determine the encoding for the value. So the returned value for

```php
$srcEncoding = strtolower(mb_detect_encoding($text));
```
will be nothing, an empty string.

**How to reproduce**  
Try to query for `google.com.tr` domain.

**Possible Solution**  
Editing the `TextHelper` class and change the following 

https://github.com/io-developer/php-whois/blob/88dc39d06e8998229eec9b98e5a1100f6b3569d2/src/Iodev/Whois/Helpers/TextHelper.php#L14 

to the following:

```php
        if ($srcEncoding != 'utf-8' && $srcEncoding !== '') {
            return mb_convert_encoding($text, 'utf-8', $srcEncoding);
        }

        if ($srcEncoding === '') {
            return mb_convert_encoding($text, 'utf-8');
        }
``` 

**Additional context**  
Just a small note, the WHOIS server `whois.metu.edu.tr` is not so stable, the first query you do will work, the second will timeout, I think they block the requests for few minutes before they reply again.

**Comment by io-developer** [comment]
Fixed in master https://github.com/io-developer/php-whois/commit/7b4f911eac592082acebcc479a3b0a15855057af
