### ISSUE TITLE
[idea] using the builtin linux whois app

### ISSUE THREAD

**Issue by linuxjuggler** [io-developer/php-whois#69]
**Description**  
Instead of using curl/sockets to communicate with the whois servers, what if we built a new loader which uses Linux whois app instead?

Just an idea that I need some feedback from you before I start trying to implement. As I am semi sure you have thought of something similar.

And make it the default one instead of the socket

**Comment by io-developer** [comment]
Well..
![image](https://user-images.githubusercontent.com/6779324/65034466-c60e9900-d94f-11e9-841c-d47fb548706f.png)

It can't be default :)

Theoretically it's possible make as alt. loader...
You can create pull request so I can make code review anyway

**Comment by linuxjuggler** [comment]
I've no problem with the current implementation or the default loader, but my idea is that instead of using CURL to communicate with the servers via telnet, we use the whois app directly.

I'll create a PR soon so you can review it. 👍

**Comment by linuxjuggler** [comment]
the latest version of Process needs at least PHP 7.1 so am not sure it will work here.

anyway, I'll figure it out for sure, lets leave it now a bit

**Comment by io-developer** [comment]
Fork v4 branch (https://github.com/io-developer/php-whois/tree/v4)
it requires php 7.2+

**Comment by io-developer** [comment]
I guess this `NativeWhoisLoader` (or whatewer) should provide customizable path to `whois` executable file. I guess it (path) can depend of client OS
