### ISSUE TITLE
[RFC] Support more whois hosts

### ISSUE THREAD

**Issue by zhuomingliang** [io-developer/php-whois#7]
Hello, 

First, thank you for developing it, I have used it by https://github.com/zhuomingliang/domain_manager, I have extended it to support more whois hosts, see https://github.com/zhuomingliang/domain_manager/blob/master/app/Console/Kernel.php#L45 for more info. It would be nice to back port to here.

**Comment by io-developer** [comment]
Hello,

Thanks for feedback and for using this lib.
I'll check your whois host list (https://github.com/zhuomingliang/domain_manager/blob/master/app/Server/WhoisServer.php). Actually add more servers is near plans :)

By the way, as I can see in your project used v1.2. Please check latest version 2.0.2 which has been refactored and bug fixed. Also latest version contains much more default whois hosts.

**Comment by zhuomingliang** [comment]
That would be great, thanks 👍

**Comment by io-developer** [comment]
Default host list extended.
Please check v2.1.0 =)

**Comment by zhuomingliang** [comment]
Thanks.
