### ISSUE TITLE
fäw.de returned as free

### ISSUE THREAD

**Issue by prey87** [io-developer/php-whois#71]
**PHP-Whois version**: 3.4

**PHP version**: 7.3

**Description**  
```
$whois->isDomainAvailable('fäw.de')
```
returns true

**Comment by io-developer** [comment]
Fixed in https://github.com/io-developer/php-whois/commit/84a6f315dabbfc545cfb31bde8b4d33fe04fbefe

**Comment by io-developer** [comment]
Fixed in master https://github.com/io-developer/php-whois/commit/3b655cbad9c827f86fd609c3f19f73100b58ae18
