### ISSUE TITLE
Docker rest service

### ISSUE THREAD

**Issue by mhf-ir** [io-developer/php-whois#90]
How about add docker image as REST service?
Using slim or any micro framework for that.

**Comment by io-developer** [comment]
It's just library.
So no plans actually =)

Anyway you can create your repo with REST docker wrapper for this lib due to MIT license

**Comment by mhf-ir** [comment]
Thanks for library btw :heart:

**Comment by io-developer** [comment]
Glad to hear that, thank you :)
