### ISSUE TITLE
Unable to connect to whois.nic.cz

### ISSUE THREAD

**Issue by mikaelz** [io-developer/php-whois#96]
**PHP-Whois version**: master

**PHP version**: 7.2.22-1+ubuntu18.04.1+deb.sury.org+1

**Description**  
I get 
```Warning: fsockopen(): unable to connect to whois.nic.cz:43 (Cannot assign requested address) in /var/www/vendor/io-developer/php-whois/src/Iodev/Whois/Loaders/SocketLoader.php on line 57``` when calling `isDomainAvailable()`

Sometimes it works, weird :/

**How to reproduce**  
`isDomainAvailable('example-test.cz')`

**Possible Solution**  
Replace `fosockopen` with `socket_create` see https://stackoverflow.com/a/25305626/289404

**Comment by io-developer** [comment]
Can't reproduce. Using latest master version.

Example:
```php
<?php

use Iodev\Whois\Whois;

require_once 'vendor/autoload.php';

$whois = Whois::create();

var_dump([
    'isDomainAvailable' => $whois->isDomainAvailable('example-test.cz'),
    'lookup' => $whois->lookupDomain('example-test.cz'),
    'info' => $whois->loadDomainInfo('example-test.cz'),
]);
```

Output:
```
php test_cz.php
array(3) {
  ["isDomainAvailable"]=>
  bool(true)
  ["lookup"]=>
  object(Iodev\Whois\Modules\Tld\DomainResponse)#885 (4) {
    ["domain":"Iodev\Whois\Modules\Tld\DomainResponse":private]=>
    string(15) "example-test.cz"
    ["query":"Iodev\Whois\Response":private]=>
    string(17) "example-test.cz
"
    ["text":"Iodev\Whois\Response":private]=>
    string(70) "Your connection limit exceeded. Please slow down and try again later.
"
    ["host":"Iodev\Whois\Response":private]=>
    string(12) "whois.nic.cz"
  }
  ["info"]=>
  NULL
}
```

Native linux cli whois:
![image](https://user-images.githubusercontent.com/6779324/72443703-c2850480-37bf-11ea-8da4-e542604dfa5e.png)

Also try `CurlLoader` instead of `SocketLoader`
